server:
  error:
    include-stacktrace: ON_PARAM
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api/produtos?&cuseSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update